#!/bin/bash

case $1 in
	-on) 
		xrandr --output HDMI1 --right-of eDP1 --mode 1920x1080 
	   	echo "Monitor switched on";;
	-off)
		xrandr --output HDMI1 --off
		echo "Monitor switched off";;
	*)
		echo -e "usage:\n\t-on\tSwitches dual monitor on\n\t-off\tSwitches dual monitor off";;
esac